Gz crypto list
gzucca/challenge-cripto-react-native pull request #2
Opened 2023-03-23 17:37 UTC by gzucca

- Home component "Main" created with empty component and button to toggle loading "CryptCards".
- CryptCards component created (will then be the one connecting with the API).
- CryptCard component created (hard-coded until connection with API).

2023-03-28 12:54 UTC, FedericoLeiva12 requested changes

2023-03-30 21:54 UTC, tomasdematos commented on src/components/CryptCard.tsx
> +type Props = {};
delete if is empty

2023-03-30 21:55 UTC, tomasdematos commented on src/components/CryptCard.tsx
> +    let roundNumber = Math.round((percentNumber + Number.EPSILON) * 100) / 100;
use conts

2023-03-30 21:58 UTC, tomasdematos commented on src/components/CryptCard.tsx
> +    if (roundNumber > 0) {
redundant components:

```
const negative = roundNumber < 0

return (
<View style={styles.percentChangeText}>
          <GainArrow width={16} height={16} fill={negative ?  "red" : "green"} />
          <Text style={styles.textGain}>{(negative ? -roundNumber : roundNumber) + '%'}</Text>
        </View>
)
```

2023-03-30 21:58 UTC, tomasdematos commented on src/components/CryptCard.tsx
> +    if (roundNumber > 0) {
also use styled components, a styled component can get props, so you can validate the color of the text inside the styles

2023-03-30 22:03 UTC, tomasdematos commented on src/components/CryptCard.tsx
> +const styles = StyleSheet.create({
styles should be stored in a separate file, the most common way to do this is with this format:

```
src/
   Components/
      AddButton/
          index.tsx <---- this file 
          styles.ts <---- move the styles here
```

2023-03-30 22:04 UTC, tomasdematos commented on src/components/CryptCards.tsx
> +      <CryptCard></CryptCard>
you can use:       <CryptCard />
if it doens't have a child

2023-04-04 15:14 UTC, closed without merging